version: '3.8'

services:
  stori:
    image: stori
    env_file: .env
    #build:
    #  context: .
    #  network: host
    ports:
      - 3000:3000
      - 27017:27017
  mongodb:
    image: mongo:latest
